### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Techn1x** [transitland/ember-leaflet-polyline-decorator#1]
Hey there!

I've been having troubles installing this addon (tried both with bower and npm). I don't think it's importing correctly? I attempted to use `{{polyline-decorator}}` as a component and it doesn't seem to be recognised, as well as this it looks like I can't use `L.Symbol()` or `L.polylineDecorator()` directly

I forked the repo and tried a few things myself to get it to import correctly but I'm not yet knowledgeable when it comes to addons/dependencies/bower/npm stuff.

I'm running ember-leaflet 3.0.12, leaflet 1.1.0 and latest ember/ember-cli

It could very well be a problem on my end so don't stress too much about it

------

Let's ignore bower for now and attempt to fix npm install since bower support in ember is going away eventually. So essentially I do the following `npm install @transitland/ember-leaflet-polyline-decorator --save-dev` - I can see that it installs to `node_modules` folder as it should.

I then notice that `leaflet-polylinedecorator` doesn't seem to get installed for me (I can't find it in `bower_components`).

Looking at this file here
https://github.com/transitland/ember-leaflet-polyline-decorator/blob/master/blueprints/ember-leaflet-polyline-decorator/index.js#L3-L13

Should there be a comma after description? That might explain why it's not being installed (but I did try this in my fork with no luck). It looks like `leaflet-polylinedecorator` now supports npm too, so maybe we should switch over to installing it that way (not sure how) and maybe that will fix the issue

I also noticed that it seems to want leaflet-0.7.2 which is a very old version of leaflet now, might be worth updating?

**Comment by Techn1x** [comment]
Looking through some of the other ember-leaflet addons, a good example to look at might be `ember-leaflet-draw`
https://github.com/StevenHeinrich/ember-leaflet-draw

They just switched from installing their leaflet-draw dependency from bower to npm, specifically in these two commits;
https://github.com/StevenHeinrich/ember-leaflet-draw/commit/2bb09573f8e84c86d483ca7226f26d591c6e1e28
https://github.com/StevenHeinrich/ember-leaflet-draw/commit/a8140cbfe42ef3b7952fd4d3a4a22dc77f4ae9a3

**Comment by Techn1x** [comment]
I'll probably give it a go on the weekend, see if I can put together a working PR, but feel free to beat me to it :)

**Comment by drewda** [comment]
Should be fixed in 0.2.0 release.

@Techn1x please comment and re-open if there are still problems with this issue.
